// VNTECH PROPRIETARY SOURCE | Owner: CÔNG TY CỔ PHẦN THƯƠNG MẠI ĐẦU TƯ PHÁT TRIỂN CÔNG NGHỆ VIỆT (VNTECH) | Product: VNTECH-KHO-MEP-001 | Fingerprint: SSOT
// VNTECH FINAL: Excel 2016 requires worksheet child elements in OpenXML schema order (autoFilter before mergeCells).
import { strToU8, zipSync } from "fflate";
import { VNTECH_BRAND } from "@/lib/vntech-brand";

type Row = Record<string, unknown>;

function xml(value: unknown) { return String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&apos;"); }
function safeFileName(value: string) { return value.replace(/[\\/:*?"<>|]+/g, "-").replace(/\s+/g, "_").slice(0, 90) || "Danh_muc_vat_tu_MEP"; }
function colName(index: number) { let result = ""; let value = index; while (value > 0) { value -= 1; result = String.fromCharCode(65 + (value % 26)) + result; value = Math.floor(value / 26); } return result; }
function downloadBlob(blob: Blob, fileName: string) { const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = fileName; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 1500); }
function blobBytes(bytes: Uint8Array): ArrayBuffer { return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer; }

type Cell = { value: string | number; style?: number; type?: "s" | "n" };
function cellXml(row: number, col: number, cell: Cell) { const ref = `${colName(col)}${row}`; const style = cell.style ? ` s="${cell.style}"` : ""; const type = cell.type ?? (typeof cell.value === "number" ? "n" : "s"); if (type === "n" && typeof cell.value === "number") return `<c r="${ref}"${style}><v>${Number.isFinite(cell.value) ? cell.value : 0}</v></c>`; return `<c r="${ref}" t="inlineStr"${style}><is><t xml:space="preserve">${xml(cell.value)}</t></is></c>`; }

export function buildMaterialCatalogXlsxBytes(materials: Row[], title = "DANH MỤC VẬT TƯ GỐC") {
  const headers = ["Mã hệ", "Tên hệ M&E", "Tên nhóm vật tư", "Mã vật tư", "Tên vật tư", "ĐVT", "Quy cách / Thông số", "Hãng / NSX", "Tồn tối thiểu"];
  const rows: Cell[][] = [[{ value: `${VNTECH_BRAND.productName} · ${title}`, style: 1 }], [{ value: "Material Master: một vật tư = một mã gốc duy nhất. Không chứa dữ liệu BOQ, đơn giá, CO/CQ hoặc MAR." }], headers.map((value) => ({ value, style: 2 }))];
  materials.forEach((item) => rows.push([
    { value: String(item.categoryCode || "") }, { value: String(item.categoryName || item.system || "") }, { value: String(item.subcategoryName || "Chưa phân nhóm") },
    { value: String(item.code || "") }, { value: String(item.name || "") }, { value: String(item.unit || "") }, { value: String(item.specification || "") }, { value: String(item.brand || "") }, { value: Number(item.minStock || 0), style: 3, type: "n" },
  ]));
  const sheetRows = rows.map((cells, rowIndex) => `<row r="${rowIndex + 1}"${rowIndex === 0 ? ' ht="28" customHeight="1"' : ""}>${cells.map((cell, colIndex) => cellXml(rowIndex + 1, colIndex + 1, cell)).join("")}</row>`).join("");
  const lastRow = Math.max(rows.length, 2);
  const sheetXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:I${lastRow}"/><sheetViews><sheetView workbookViewId="0"><pane ySplit="3" topLeftCell="A4" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="2" width="18" customWidth="1"/><col min="3" max="3" width="28" customWidth="1"/><col min="4" max="4" width="18" customWidth="1"/><col min="5" max="5" width="42" customWidth="1"/><col min="6" max="6" width="10" customWidth="1"/><col min="7" max="8" width="24" customWidth="1"/><col min="9" max="9" width="16" customWidth="1"/></cols><sheetData>${sheetRows}</sheetData><autoFilter ref="A3:I${lastRow}"/><mergeCells count="2"><mergeCell ref="A1:I1"/><mergeCell ref="A2:I2"/></mergeCells><pageMargins left="0.25" right="0.25" top="0.4" bottom="0.4" header="0.2" footer="0.2"/><pageSetup orientation="landscape" paperSize="9" fitToWidth="1" fitToHeight="0"/></worksheet>`;
  const stylesXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="1"><numFmt numFmtId="164" formatCode="#,##0.###"/></numFmts><fonts count="3"><font><sz val="10"/><name val="Aptos"/></font><font><b/><sz val="16"/><color rgb="FFFFFFFF"/><name val="Aptos Display"/></font><font><b/><sz val="10"/><color rgb="FFFFFFFF"/><name val="Aptos"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF0B6FA4"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="2"><border><left/><right/><top/><bottom/><diagonal/></border><border><left style="thin"><color rgb="FFD5E0E6"/></left><right style="thin"><color rgb="FFD5E0E6"/></right><top style="thin"><color rgb="FFD5E0E6"/></top><bottom style="thin"><color rgb="FFD5E0E6"/></bottom><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="5"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf><xf numFmtId="0" fontId="2" fillId="2" borderId="1" xfId="0" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf><xf numFmtId="164" fontId="0" fillId="0" borderId="1" xfId="0" applyNumberFormat="1" applyAlignment="1"><alignment horizontal="right" vertical="center"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;
  const archive: Record<string, Uint8Array> = {
    "[Content_Types].xml": strToU8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>`),
    "_rels/.rels": strToU8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`),
    "xl/workbook.xml": strToU8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><bookViews><workbookView/></bookViews><sheets><sheet name="Danh mục vật tư gốc" sheetId="1" r:id="rId1"/></sheets></workbook>`),
    "xl/_rels/workbook.xml.rels": strToU8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`),
    "xl/styles.xml": strToU8(stylesXml), "xl/worksheets/sheet1.xml": strToU8(sheetXml),
  };
  return zipSync(archive, { level: 6 });
}
export function downloadMaterialCatalogXlsx(materials: Row[], fileName = "Danh_muc_vat_tu_goc", title = "DANH MỤC VẬT TƯ GỐC") {
  const bytes = buildMaterialCatalogXlsxBytes(materials, title);
  downloadBlob(new Blob([blobBytes(bytes)], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), `${safeFileName(fileName)}.xlsx`);
}
