// PHASE 1 (U-11) — MODULE DÙNG CHUNG TÁCH KHỎI `app/page.tsx`.
//
// Vì sao tách: `app/page.tsx` là MỘT tệp khổng lồ (hơn 4.000 dòng, hơn 250 khai báo top-level).
// Thứ tự cắt ĐÚNG (đã ghi ở `docs/agent-progress/U14-U11-KHAO-SAT.md` mục 2): tách HELPER DÙNG CHUNG trước
// (gỡ chặn IMPORT VÒNG), rồi mới tách từng màn.
//
// ⚠️ ĐIỀU KIỆN AN TOÀN (do `tools/tach-lat-cat-page.mjs` tự kiểm TRƯỚC KHI GHI): mọi tên mà các khối ở đây
// tham chiếu phải thuộc (a) khối cùng nằm trong tệp này, (b) tên có sẵn của JS, (c) tên đến từ `import` của
// `page.tsx` — công cụ SINH LẠI import đó ở đây, hoặc (d) kiểu của React ⇒ `import type … from "react"`.
// Không còn tên nào khác ⇒ KHÔNG thể tạo import vòng.

import { ActivityTimeline, DataTable, ListToolbar, StatusBadge } from "@/app/components/ui";
import { AttachmentPanel, CardHead, Empty, Kpi, date, downloadDeliveredPdf, exportDeliveredCsv, exportDeliveredXlsx, format, initials } from "@/lib/ui-shared";
import type { AppData, Row } from "@/lib/ui-shared";
import { useState } from "react";
function Delivered({ data, project, open }: { data: AppData; project: string; open: (name: string, row?: Row) => void }) {
  const rows=data.receipts.filter((row)=>(project==="ALL"||row.projectId===project)&&row.bchConfirmationStatus==="confirmed"); const acceptedTotal=rows.reduce((sum,row)=>sum+Number(row.acceptedQty||0),0); const selected=rows[0]; const [advanced,setAdvanced]=useState(false);
  // MT2-P8-12 (§6.13 ①) — «Đơn hàng đã giao: Thêm Search · Sort · Filter». ⚠️ Lọc THẬT trên `rows`.
  const [q,setQ]=useState(""); const [sortKey,setSortKey]=useState("receivedAt_desc"); const [statusFilter,setStatusFilter]=useState("ALL"); const [supplierFilter2,setSupplierFilter2]=useState("ALL");
  const supplierOptions=Array.from(new Set(rows.map((row)=>String(row.supplierName||"")).filter(Boolean))).sort();
  const statusOptions=Array.from(new Set(rows.map((row)=>String(row.postingStatus||"")))).filter(Boolean);
  const visibleRows=rows.filter((row)=>{const hay=`${row.poNo||""} ${row.projectName||row.projectCode||""} ${row.supplierName||""} ${row.warehouseName||""}`.toLowerCase();return (!q||hay.includes(q.toLowerCase()))&&(statusFilter==="ALL"||String(row.postingStatus||"")===statusFilter)&&(supplierFilter2==="ALL"||String(row.supplierName||"")===supplierFilter2);}).sort((a,b)=>{if(sortKey==="receivedAt_asc")return String(a.receivedAt||"").localeCompare(String(b.receivedAt||""));if(sortKey==="poNo")return String(a.poNo||"").localeCompare(String(b.poNo||""));if(sortKey==="supplier")return String(a.supplierName||"").localeCompare(String(b.supplierName||""));return String(b.receivedAt||"").localeCompare(String(a.receivedAt||""));});
  return <div className="stack module-screen delivered-screen baseline-screen"><div className="screen-toolbar report-export-toolbar"><div></div><div className="row-actions"><button className="secondary" onClick={()=>exportDeliveredXlsx(rows)}>▣ Xuất Excel</button><button className="secondary" onClick={()=>exportDeliveredCsv(rows)}>▣ Xuất CSV</button><button className="secondary danger-outline" onClick={()=>downloadDeliveredPdf(rows)}>▣ Xuất PDF</button><button className={advanced?"secondary active":"secondary"} onClick={()=>setAdvanced(v=>!v)}>⚲ Lọc nâng cao</button></div></div>{advanced&&<section className="card compact-functional-filter"><span>Đang áp dụng phạm vi dự án ở thanh dự án phía trên.</span><button className="secondary" onClick={()=>setAdvanced(false)}>ĐÓNG BỘ LỌC</button></section>}<div className="kpi-grid"><Kpi icon="DG" label="Đơn đã giao đủ" value={format.format(rows.filter((row)=>Number(row.acceptedQty)>=Number(row.orderedQty||row.acceptedQty)).length)} note="↑ so với kỳ trước" tone="green"/><Kpi icon="MP" label="Giao một phần" value={format.format(rows.filter((row)=>Number(row.acceptedQty)<Number(row.orderedQty||row.acceptedQty)).length)} note="↑ theo dõi giao tiếp"/><Kpi icon="XN" label="Chờ BCH xác nhận" value={format.format(data.receipts.filter((row)=>row.bchConfirmationStatus==="pending").length)} note="↑ cần xử lý" tone="amber"/><Kpi icon="NK" label="Đã nhập kho" value={format.format(acceptedTotal)} note="↑ số lượng được chấp nhận" tone="violet"/></div>
    <section className="card delivered-table-card"><ListToolbar title="Đơn hàng đã giao" note="Search · Sort · Filter (§6.13)" count={visibleRows.length} total={rows.length} unit="dòng" search={{value:q,onChange:setQ,placeholder:"Tìm PO · dự án · NCC · kho nhận"}} sort={{value:sortKey,onChange:setSortKey,options:[{value:"receivedAt_desc",label:"Ngày giao — mới nhất"},{value:"receivedAt_asc",label:"Ngày giao — cũ nhất"},{value:"poNo",label:"Mã PO"},{value:"supplier",label:"Nhà cung cấp"}]}} filters={[{key:"status",label:"Tình trạng",value:statusFilter,onChange:setStatusFilter,options:[{value:"ALL",label:"Tất cả tình trạng"},...statusOptions.map((v)=>({value:v,label:v}))]},{key:"supplier",label:"Nhà cung cấp",value:supplierFilter2,onChange:setSupplierFilter2,options:[{value:"ALL",label:"Tất cả nhà cung cấp"},...supplierOptions.map((v)=>({value:v,label:v}))]}]} /><DataTable rows={visibleRows} rowKey={(row) => String(row.id)} columns={[{ key: "c1", header: "PO", render: (row) => <><strong className="link">{row.poNo}</strong></> }, { key: "c2", header: "DỰ ÁN", render: (row) => <>{row.projectName||row.projectCode}</> }, { key: "c3", header: "NHÀ CUNG CẤP", render: (row) => <>{row.supplierName}</> }, { key: "c4", header: "KHO NHẬN", render: (row) => <>{row.warehouseName||"KHO CÔNG TRƯỜNG"}</> }, { key: "c5", header: "NGÀY GIAO", render: (row) => <>{date(row.receivedAt)}</> }, { key: "c6", header: "BCH XÁC NHẬN", render: (row) => <><span className="person-cell"><i className="mini-avatar">{initials(String(row.bchConfirmedByName||"BCH"))}</i><span>{row.bchConfirmedByName||"BCH công trường"}<small>{date(row.bchConfirmedAt)}</small></span></span></> }, { key: "c7", header: "CHỨNG CHỈ", render: (row) => <><span className="link">▧ {row.certificateCount||0}</span></> }, { key: "c8", header: "ẢNH", render: (row) => <><span className="violet-text">▧ {row.attachmentCount||0}</span></> }, { key: "c9", header: "TÌNH TRẠNG", render: (row) => <><StatusBadge value={row.postingStatus==="posted"?"Đã nhập kho":row.postingStatus==="pending_confirmation"?"Chờ hạch toán":row.postingStatus==="unposted"?"Chưa hạch toán":String(row.postingStatus||"Chờ hạch toán")}/></> }, { key: "c10", header: "THAO TÁC", render: (row) => <><button type="button" className="export-mini" data-vntech="delivered-detail-open" title="Chi tiết đơn giao hàng" onClick={()=>open("receiptDetail",row)}>Chi tiết đơn giao hàng</button></> }]} emptyText="Chưa có đơn hàng hoàn tất xác nhận." /></section>
    {/* MT2-P8-12 (§6.13 ⑥) — ĐÃ GOM 3 khối (Lịch sử giao nhận · Chứng chỉ/Tài liệu · Ảnh giao hàng) vào
        MODAL «Chi tiết đơn giao hàng» (`ReceiptDrawer.tsx`). ⛔ KHÔNG còn hiển thị TRỰC TIẾP BÊN NGOÀI
        danh sách đơn hàng — mở modal từ nút «Chi tiết đơn giao hàng» ở cột THAO TÁC. */}
  </div>;
}
export {
  Delivered,
};