// PHASE 1 (U-11) — MODULE DÙNG CHUNG TÁCH KHỎI `app/page.tsx`.
//
// Vì sao tách: `app/page.tsx` là MỘT tệp khổng lồ (hơn 4.000 dòng, hơn 250 khai báo top-level).
// Thứ tự cắt ĐÚNG (đã ghi ở `docs/agent-progress/U14-U11-KHAO-SAT.md` mục 2): tách HELPER DÙNG CHUNG trước
// (gỡ chặn IMPORT VÒNG), rồi mới tách từng màn.
//
// ⚠️ ĐIỀU KIỆN AN TOÀN (do `tools/tach-lat-cat-page.mjs` tự kiểm TRƯỚC KHI GHI): mọi tên mà các khối ở đây
// tham chiếu phải thuộc (a) khối cùng nằm trong tệp này, (b) tên có sẵn của JS, (c) tên đến từ `import` của
// `page.tsx` — công cụ SINH LẠI import đó ở đây, hoặc (d) kiểu của React ⇒ `import type … from "react"`.
// Không còn tên nào khác ⇒ KHÔNG thể tạo import vòng.

import { ActivityTimeline, DataTable, ListToolbar, StatusBadge } from "@/app/components/ui";
import { AttachmentPanel, CardHead, Empty, Kpi, date, downloadDeliveredPdf, exportDeliveredCsv, exportDeliveredXlsx, format, initials } from "@/lib/ui-shared";
import type { AppData, Row } from "@/lib/ui-shared";
import { useState } from "react";
function Delivered({ data, project, open }: { data: AppData; project: string; open: (name: string, row?: Row) => void }) {
  const rows=data.receipts.filter((row)=>(project==="ALL"||row.projectId===project)&&row.bchConfirmationStatus==="confirmed"); const acceptedTotal=rows.reduce((sum,row)=>sum+Number(row.acceptedQty||0),0); const selected=rows[0]; const [advanced,setAdvanced]=useState(false);
  return <div className="stack module-screen delivered-screen baseline-screen"><div className="screen-toolbar report-export-toolbar"><div></div><div className="row-actions"><button className="secondary" onClick={()=>exportDeliveredXlsx(rows)}>▣ Xuất Excel</button><button className="secondary" onClick={()=>exportDeliveredCsv(rows)}>▣ Xuất CSV</button><button className="secondary danger-outline" onClick={()=>downloadDeliveredPdf(rows)}>▣ Xuất PDF</button><button className={advanced?"secondary active":"secondary"} onClick={()=>setAdvanced(v=>!v)}>⚲ Lọc nâng cao</button></div></div>{advanced&&<section className="card compact-functional-filter"><span>Đang áp dụng phạm vi dự án ở thanh dự án phía trên.</span><button className="secondary" onClick={()=>setAdvanced(false)}>ĐÓNG BỘ LỌC</button></section>}<div className="kpi-grid"><Kpi icon="DG" label="Đơn đã giao đủ" value={format.format(rows.filter((row)=>Number(row.acceptedQty)>=Number(row.orderedQty||row.acceptedQty)).length)} note="↑ so với kỳ trước" tone="green"/><Kpi icon="MP" label="Giao một phần" value={format.format(rows.filter((row)=>Number(row.acceptedQty)<Number(row.orderedQty||row.acceptedQty)).length)} note="↑ theo dõi giao tiếp"/><Kpi icon="XN" label="Chờ BCH xác nhận" value={format.format(data.receipts.filter((row)=>row.bchConfirmationStatus==="pending").length)} note="↑ cần xử lý" tone="amber"/><Kpi icon="NK" label="Đã nhập kho" value={format.format(acceptedTotal)} note="↑ số lượng được chấp nhận" tone="violet"/></div>
    <section className="card delivered-table-card"><ListToolbar title="Đơn hàng đã giao" note="Đang hiển thị toàn bộ" count={rows.length} unit="dòng" /><DataTable rows={rows} rowKey={(row) => String(row.id)} columns={[{ key: "c1", header: "PO", render: (row) => <><strong className="link">{row.poNo}</strong></> }, { key: "c2", header: "DỰ ÁN", render: (row) => <>{row.projectName||row.projectCode}</> }, { key: "c3", header: "NHÀ CUNG CẤP", render: (row) => <>{row.supplierName}</> }, { key: "c4", header: "KHO NHẬN", render: (row) => <>{row.warehouseName||"KHO CÔNG TRƯỜNG"}</> }, { key: "c5", header: "NGÀY GIAO", render: (row) => <>{date(row.receivedAt)}</> }, { key: "c6", header: "BCH XÁC NHẬN", render: (row) => <><span className="person-cell"><i className="mini-avatar">{initials(String(row.bchConfirmedByName||"BCH"))}</i><span>{row.bchConfirmedByName||"BCH công trường"}<small>{date(row.bchConfirmedAt)}</small></span></span></> }, { key: "c7", header: "CHỨNG CHỈ", render: (row) => <><span className="link">▧ {row.certificateCount||0}</span></> }, { key: "c8", header: "ẢNH", render: (row) => <><span className="violet-text">▧ {row.attachmentCount||0}</span></> }, { key: "c9", header: "TÌNH TRẠNG", render: (row) => <><StatusBadge value={row.postingStatus==="posted"?"Đã nhập kho":row.postingStatus==="pending_confirmation"?"Chờ hạch toán":row.postingStatus==="unposted"?"Chưa hạch toán":String(row.postingStatus||"Chờ hạch toán")}/></> }, { key: "c10", header: "THAO TÁC", render: (row) => <><button className="icon-mini" onClick={()=>open("receiptDetail",row)}>◉</button></> }]} emptyText="Chưa có đơn hàng hoàn tất xác nhận." /></section>
    <div className="delivered-detail-grid">{selected?<ActivityTimeline title="Lịch sử giao nhận" note="Chỉ hiển thị mốc thời gian đã ghi nhận trên hồ sơ" items={[{ action: "BCH đã xác nhận giao hàng", actor: selected.bchConfirmedByName || "BCH công trường", at: selected.bchConfirmedAt, tone: "green" as const }, { action: "Kho ghi nhận nhận hàng", actor: selected.warehouseName || "Kho công trường", at: selected.receivedAt, tone: "blue" as const }, ...(selected.createdAt ? [{ action: "Tạo hồ sơ giao nhận", actor: selected.poNo || "Theo PO", at: selected.createdAt, tone: "blue" as const }] : [])]} />:<Empty text="Chưa có giao nhận thực tế để hiển thị lịch sử."/>}<section className="card"><CardHead title="Chứng chỉ / Tài liệu đã tải lên" note="Tải lên và tải xuống trực tiếp từ hồ sơ giao nhận"/>{selected?<AttachmentPanel entityType="goods_receipt" entityId={selected.id}/>:<Empty text="Chưa có chuyến giao để hiển thị hồ sơ."/>}</section><section className="card"><CardHead title="Ảnh giao hàng" note="Hiển thị và tải từ đúng hồ sơ giao nhận, không dùng ảnh minh họa giả"/>{selected?<div className="delivery-photo-files"><AttachmentPanel entityType="goods_receipt" entityId={selected.id}/></div>:<Empty text="Chưa có chuyến giao để hiển thị ảnh."/>}</section></div>
  </div>;
}
export {
  Delivered,
};