// PHASE 1 (U-11) — MODULE DÙNG CHUNG TÁCH KHỎI `app/page.tsx`.
//
// Vì sao tách: `app/page.tsx` là MỘT tệp khổng lồ (hơn 4.000 dòng, hơn 250 khai báo top-level).
// Thứ tự cắt ĐÚNG (đã ghi ở `docs/agent-progress/U14-U11-KHAO-SAT.md` mục 2): tách HELPER DÙNG CHUNG trước
// (gỡ chặn IMPORT VÒNG), rồi mới tách từng màn.
//
// ⚠️ ĐIỀU KIỆN AN TOÀN (do `tools/tach-lat-cat-page.mjs` tự kiểm TRƯỚC KHI GHI): mọi tên mà các khối ở đây
// tham chiếu phải thuộc (a) khối cùng nằm trong tệp này, (b) tên có sẵn của JS, (c) tên đến từ `import` của
// `page.tsx` — công cụ SINH LẠI import đó ở đây, hoặc (d) kiểu của React ⇒ `import type … from "react"`.
// Không còn tên nào khác ⇒ KHÔNG thể tạo import vòng.

import { StatusBadge } from "@/app/components/ui";
import { isAdminUser } from "@/lib/permissions";
import { CardHead, Empty, NavIcon, UI_TODAY, date, money } from "@/lib/ui-shared";
import type { AppData, Row } from "@/lib/ui-shared";
import { FormEvent } from "react";
function ProjectTeams({data,project,open,action}:{data:AppData;project:string;open:(name:string,row?:Row)=>void;action:(name:string,payload:Row)=>Promise<boolean>}){
  const selectedProject=project==="ALL"?null:project; const teams=data.teams.filter(row=>row.projectId===selectedProject); const projectRow=data.projects.find(row=>row.id===selectedProject); const canManage=isAdminUser(data.user)||["cht","commander","da_truong"].includes(String(data.user.role));
  const contracts=data.teamSubcontracts.filter(r=>r.projectId===selectedProject); const productions=data.teamProductionRecords.filter(r=>r.projectId===selectedProject); const payments=data.teamPayments.filter(r=>r.projectId===selectedProject); const settlements=data.teamSettlements.filter(r=>r.projectId===selectedProject);
  // Project-team commercial management is independent from warehouse issue/return operations.
  // không thao tác xuất kho tại màn này; cấp phát/hoàn trả vật tư chỉ thực hiện tại KHO VẬT TƯ → Xuất kho theo tổ đội.
  async function submitContract(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedProject)return;const f=Object.fromEntries(new FormData(e.currentTarget));if(await action("save_team_subcontract",{...f,projectId:selectedProject}))(e.currentTarget as HTMLFormElement).reset();}
  async function submitProduction(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedProject)return;const f=Object.fromEntries(new FormData(e.currentTarget));if(await action("save_team_production",{...f,projectId:selectedProject}))(e.currentTarget as HTMLFormElement).reset();}
  async function submitPayment(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedProject)return;const f=Object.fromEntries(new FormData(e.currentTarget));if(await action("save_team_payment",{...f,projectId:selectedProject}))(e.currentTarget as HTMLFormElement).reset();}
  return <div className="stack"><section className="team-banner project-team-banner"><div><span>TỔ ĐỘI / NHÀ THẦU PHỤ</span><h2>{projectRow?.code||"—"} · {projectRow?.name||"Chưa có dự án"}</h2><p>Hợp đồng giao khoán và thanh toán tổ đội là nghiệp vụ độc lập với Hợp đồng chính dự án. Kho chỉ liên kết bằng team_id để truy vết vật tư cấp/hoàn.</p></div></section>
  {canManage&&selectedProject&&<section className="card"><CardHead title="Hợp đồng giao khoán tổ đội" note="Hợp đồng độc lập; không dùng contract_payments/BOQ hợp đồng chính."/><form className="payment-entry-inline" onSubmit={submitContract}><select name={"teamId"} required defaultValue=""><option value="">Chọn tổ đội</option>{teams.map(t=><option key={t.id} value={t.id}>{t.code} · {t.name}</option>)}</select><input name="contractNo" placeholder="Số HĐ giao khoán" required/><input name="contractName" placeholder="Tên/phạm vi hợp đồng" required/><input name="scopeText" placeholder="Phạm vi công việc"/><input name="contractValue" type="number" min="0" step="1" placeholder="Giá trị giao khoán" required/><input name="startDate" type="date"/><input name="endDate" type="date"/><button className="primary">LƯU HỢP ĐỒNG</button></form></section>}
  <section className="card"><CardHead title="Danh sách tổ đội dự án" note="Sản lượng, thanh toán và quyết toán lấy từ sổ độc lập của từng hợp đồng giao khoán."/><div className="table-wrap"><table><thead><tr><th>Tổ đội</th><th>Hợp đồng giao khoán</th><th>Giá trị HĐ</th><th>Sản lượng duyệt</th><th>Đã thanh toán</th><th>Còn phải trả</th><th>Quyết toán</th><th>Trạng thái</th></tr></thead><tbody>{teams.map(team=>{const cs=contracts.filter(c=>c.teamId===team.id);const cv=cs.reduce((a,c)=>a+Number(c.contractValue||0),0);const approved=productions.filter(r=>r.teamId===team.id&&r.status==="approved").reduce((a,r)=>a+Number(r.approvedValue||0),0);const paid=payments.filter(r=>r.teamId===team.id).reduce((a,r)=>a+Number(r.amount||0),0);const settlement=settlements.find(r=>r.teamId===team.id&&r.status==="closed");return <tr key={team.id}><td><strong>{team.code}</strong><small>{team.name} · {team.trade||"—"}</small></td><td>{cs.map(c=><div key={c.id}><strong>{c.contractNo}</strong><small>{c.contractName}</small></div>)}{!cs.length&&<span className="muted">Chưa lập</span>}</td><td>{money(cv)}</td><td><strong>{money(approved)}</strong></td><td>{money(paid)}</td><td><strong>{money(Math.max(0,approved-paid))}</strong></td><td><StatusBadge value={settlement?"Đã quyết toán":"Chưa quyết toán"}/>{canManage&&!settlement&&cs.length===1&&<button className="export-mini" onClick={()=>window.confirm(`Quyết toán ${cs[0].contractNo}? Hệ thống sẽ chặn nếu tổ đội còn vật tư chưa xử lý.`)&&action("settle_team_subcontract",{subcontractId:cs[0].id,settlementNo:`QT-${cs[0].contractNo}`,adjustmentValue:0})}>Quyết toán</button>}</td><td><StatusBadge value={team.active===0?"Ngừng hoạt động":"Đang hoạt động"}/></td></tr>})}{!teams.length&&<tr><td colSpan={8}><Empty text="Chưa có tổ đội trong dự án đang chọn."/></td></tr>}</tbody></table></div></section>
  {canManage&&contracts.length>0&&<div className="two-col"><section className="card"><CardHead title="Nghiệm thu sản lượng tổ đội" note="Tách hoàn toàn với Báo cáo sản lượng hợp đồng chính."/><form className="stack-form" onSubmit={submitProduction}><select name="subcontractId" required defaultValue=""><option value="">Chọn HĐ giao khoán</option>{contracts.map(c=><option key={c.id} value={c.id}>{c.contractNo} · {c.teamName}</option>)}</select><input name="periodKey" type="month" required/><input name="referenceNo" placeholder="Biên bản nghiệm thu"/><input name="description" placeholder="Nội dung nghiệm thu" required/><input name="submittedValue" type="number" min="0" step="1" placeholder="Giá trị trình" required/><input name="approvedValue" type="number" min="0" step="1" placeholder="Giá trị duyệt" required/><button className="primary">GHI NHẬN SẢN LƯỢNG</button></form><div className="simple-list">{productions.slice(0,8).map(r=><div key={r.id}><span className="doc-icon"><NavIcon name="project_progress"/></span><div><strong>{r.contractNo} · {r.periodKey}</strong><p>{r.teamName} · {r.referenceNo||"—"}</p></div><b>{money(r.approvedValue)}</b>{r.status!=="approved"&&<button className="mini-approve" onClick={()=>action("approve_team_production",{productionId:r.id})}>Duyệt</button>}</div>)}</div></section><section className="card"><CardHead title="Tạm ứng / Thanh toán tổ đội" note="Thanh toán riêng cho HĐ giao khoán; không ghi vào Thanh toán HĐ chính."/><form className="stack-form" onSubmit={submitPayment}><select name="subcontractId" required defaultValue=""><option value="">Chọn HĐ giao khoán</option>{contracts.map(c=><option key={c.id} value={c.id}>{c.contractNo} · {c.teamName}</option>)}</select><select name="paymentType" defaultValue="progress"><option value="advance">Tạm ứng</option><option value="progress">Thanh toán sản lượng</option><option value="retention">Hoàn giữ lại</option><option value="settlement">Quyết toán</option></select><input name="paymentDate" type="date" defaultValue={UI_TODAY} required/><input name="referenceNo" placeholder="Chứng từ"/><input name="description" placeholder="Nội dung" required/><input name="amount" type="number" min="0" step="1" placeholder="Số tiền" required/><button className="primary">GHI THANH TOÁN</button></form><div className="simple-list">{payments.slice(0,8).map(r=><div key={r.id}><span className="doc-icon"><NavIcon name="payments"/></span><div><strong>{r.contractNo} · {r.description}</strong><p>{r.teamName} · {r.paymentDate}</p></div><b>{money(r.amount)}</b></div>)}</div></section></div>}
  </div>;
}

export {
  ProjectTeams,
};