// PHASE 2 (§21) — MÀN CHI TIẾT PO (ĐƠN MUA).
//
// Vì sao tách thành tệp riêng trong `app/screens/`: `docs/agent-progress/PHASE2-GAP-ANALYSIS.md` §5.2 đo
// «THIẾU HOÀN TOÀN màn chi tiết PO» — trước đây chỉ có chi tiết GRN (`ReceiptDrawer.tsx`). Ở đây KHÔNG
// thêm action/API nào: mọi số liệu lấy từ payload bootstrap đã có (`data.purchaseOrders`, `data.receipts`)
// và từ hàm thuần `lib/p2-po-trace.ts` (đã có test hợp đồng riêng).
//
// BỐN PHẦN BẮT BUỘC CỦA §21 (đúng thứ tự, mỗi phần có dấu `data-vntech` để test hợp đồng đo được):
//   1. `po-source-pr`     — PO sinh từ phiếu nào; `request_id = NULL` ⇒ hiện RÕ «PO mồ côi — không truy được PR».
//   2. `po-summary-table` — Ordered / Received / Remaining (`purchase_order_items.ordered_qty`/`received_qty`/`closed_qty`).
//   3. `po-grn-list`      — mã GRN · ngày · trạng thái · SỐ DÒNG; GRN RỖNG DÒNG ⇒ CẢNH BÁO ĐỎ (10/16 GRN thật đang rỗng).
//   4. `po-timeline`      — TÁI DÙNG `ActivityTimeline` (`app/components/ui/Timeline.tsx`), CHỈ dựng từ mốc THẬT.
//
// ⚠️ KHÔNG BỊA SỐ: thiếu nguồn ⇒ hiện «chưa có nguồn» + LÝ DO lấy từ `quantityAudit().reason`.

import { ActivityTimeline, EntityDetailModal, StatusBadge } from "@/app/components/ui";
import { statusLabel } from "@/lib/labels";
import { isEmptyReceipt, isOrphanPurchaseOrder, numeric, poLineLabel, purchaseOrderTimeline, quantityAudit, receiptItemCount, receiptsForPurchaseOrder } from "@/lib/p2-po-trace";
import { format } from "@/lib/ui-shared";
import type { AppData, Row } from "@/lib/ui-shared";

function PurchaseOrderDrawer({ data, purchaseOrder, close, open }: { data: AppData; purchaseOrder: Row; close: () => void; open: (name: string, row?: Row) => void }) {
  // Số liệu CHỈ lấy từ payload + hàm thuần dùng chung — KHÔNG nội suy, KHÔNG tự cộng trong JSX.
  const audit = quantityAudit(purchaseOrder);
  const orphan = isOrphanPurchaseOrder(purchaseOrder);
  const deliveryPercent = audit.ordered > 0 ? Math.min(100, (audit.received + audit.closed) / audit.ordered * 100) : 0;
  const poItems: Row[] = Array.isArray(purchaseOrder.items) ? purchaseOrder.items : [];
  // Truy vết ngược (§20 ⇄ §21): đóng PO rồi mở lại chi tiết phiếu đề nghị nguồn.
  const openSourceRequest = () => { if (!orphan) { close(); open("detail", { id: purchaseOrder.requestId, requestNo: purchaseOrder.requestNo }); } };
  return <div className="overlay page-mode"><EntityDetailModal open onClose={close} title={`CHI TIẾT ĐƠN MUA · ${purchaseOrder.poNo || purchaseOrder.id}`} subtitle={<>{purchaseOrder.projectCode} · {purchaseOrder.supplierName || "Chưa xác định nhà cung cấp"} · {statusLabel(purchaseOrder)}</>} entityId={String(purchaseOrder.poNo || purchaseOrder.id)} width="wide" tabs={[{ key: "po-detail", label: "Chi tiết PO", content: <><header><div><small className="document-name">ĐƠN MUA (PURCHASE ORDER)</small><strong>{purchaseOrder.poNo || purchaseOrder.id}</strong><StatusBadge value={statusLabel(purchaseOrder)} /><p>{purchaseOrder.projectCode} · {purchaseOrder.supplierName || "Chưa xác định nhà cung cấp"}</p></div><button className="page-back" onClick={close} title="Quay lại danh sách">← Quay lại</button></header><div className="drawer-body">
    <section className="summary-grid request-summary"><div><small>Nhà cung cấp</small><strong>{purchaseOrder.supplierName || "Chưa xác định"}</strong></div><div><small>Dự án</small><strong>{purchaseOrder.projectCode || "—"}</strong></div><div><small>Ngày phát hành</small><strong>{purchaseOrder.orderedAt ? String(purchaseOrder.orderedAt).slice(0, 10) : "—"}</strong></div><div><small>Hạn giao dự kiến (ETA)</small><strong>{purchaseOrder.eta ? String(purchaseOrder.eta).slice(0, 10) : "—"}</strong></div><div><small>Trạng thái đơn</small><strong>{statusLabel(purchaseOrder)}</strong></div><div><small>Trạng thái giao nhận</small><strong>{purchaseOrder.deliveryCompletedAt ? "Đã hoàn tất giao nhận" : purchaseOrder.deliveryQueuedAt ? "Đang trong hàng chờ giao" : "Chưa vào hàng chờ giao"}</strong></div><div><small>Số dòng đặt</small><strong>{poItems.length || numeric(purchaseOrder.itemCount)} dòng</strong></div><div><small>Số chuyến giao (GRN)</small><strong>{(data.receipts || []).filter((receipt: Row) => String(receipt.purchaseOrderId) === String(purchaseOrder.id)).length}</strong></div></section>
    <section className="drawer-section po-source-pr" data-vntech="po-source-pr"><div className="card-head"><div><h2>Nguồn PR (phiếu đề nghị)</h2><p>PO sinh từ phiếu đề nghị nào — truy vết xuôi theo `purchase_orders.request_id`</p></div></div>{orphan?<div className="inline-alert danger" data-vntech="po-source-pr-orphan"><b>⚠ PO mồ côi — không truy được PR.</b> Bản ghi này có <code>request_id = NULL</code> nên KHÔNG xác định được phiếu đề nghị nguồn. Cần gán lại `request_id` trước khi tin cậy số liệu đối soát PR ↔ PO.</div>:<div className="summary-grid request-summary"><div><small>Số phiếu đề nghị</small><strong>{purchaseOrder.requestNo || purchaseOrder.requestId}</strong></div><div><small>Mã kỹ thuật (request_id)</small><strong>{purchaseOrder.requestId}</strong></div><div><small>Mở lại phiếu</small><button type="button" className="secondary" data-vntech="po-source-pr-open" onClick={openSourceRequest}>◉ Xem phiếu đề nghị nguồn</button></div></div>}</section>
    <section className="drawer-section po-summary-table" data-vntech="po-summary-table"><div className="card-head"><div><h2>Khối lượng đặt / đã nhận / còn lại</h2><p>{audit.hasData?`Nguồn số liệu: ${audit.source === "po_header" ? "tổng hợp đầu PO" : "cộng từ dòng PO"} · đối chiếu ${receiptsForPurchaseOrder(data, purchaseOrder.id).length} chuyến giao`:"Chưa có nguồn số liệu"}</p></div></div>{audit.hasData?<><div className="table-wrap"><table className="data-table"><thead><tr><th>Đã đặt (ordered)</th><th>Đã nhận (received)</th><th>Đóng thiếu (closed)</th><th>Còn lại (remaining)</th><th>Thực giao theo GRN</th></tr></thead><tbody><tr><td><strong>{format.format(numeric(audit.ordered))}</strong></td><td><strong className="green-text">{format.format(numeric(audit.received))}</strong></td><td>{format.format(numeric(audit.closed))}</td><td><strong className={audit.remaining > 0 ? "red-text" : "green-text"}>{format.format(numeric(audit.remaining))}</strong></td><td>{format.format(numeric(audit.delivered))}</td></tr></tbody></table></div><p className="vt-timeline-note">Tiến độ nhận theo số lượng backend ghi nhận: {deliveryPercent.toLocaleString("vi-VN", { maximumFractionDigits: 2 })}%{audit.remaining > 0 ? ` · còn ${format.format(numeric(audit.remaining))} chưa nhận` : " · đã nhận đủ theo dòng PO"}</p></>:<div className="inline-alert" data-vntech="po-summary-nosource"><b>chưa có nguồn số lượng.</b> {audit.reason} UI KHÔNG nội suy số 0 thay cho dữ liệu thiếu.</div>}{poItems.length>0&&<div className="table-wrap"><table className="data-table"><thead><tr><th>Dòng PO</th><th>SL đặt</th><th>SL nhận</th><th>SL đóng thiếu</th><th>Còn lại</th><th>Trạng thái dòng</th></tr></thead><tbody>{poItems.map((item: Row, index: number) => <tr key={item.id || index}><td>{poLineLabel(item, index)}</td><td>{format.format(numeric(item.orderedQty))}</td><td>{format.format(numeric(item.receivedQty))}</td><td>{format.format(numeric(item.closedQty))}</td><td className={numeric(item.remainingQty) > 0 ? "red-text" : "green-text"}>{format.format(numeric(item.remainingQty))}</td><td><StatusBadge value={item.status === "received" ? "Đã nhận đủ" : item.status === "partial_delivery" ? "Giao một phần" : item.status === "delivered_pending_confirmation" ? "Chờ BCH xác nhận" : "Đang mua"} /></td></tr>)}</tbody></table></div>}</section>
    <section className="drawer-section po-grn-list" data-vntech="po-grn-list">{(() => { const receipts = receiptsForPurchaseOrder(data, purchaseOrder.id); const emptyReceipts = receipts.filter((receipt) => isEmptyReceipt(receipt)); const deliveredQty = receipts.reduce((sum, receipt) => sum + numeric(receipt.actualDeliveredQty), 0); const acceptedQty = receipts.reduce((sum, receipt) => sum + numeric(receipt.acceptedQty), 0); return <><div className="card-head"><div><h2>Danh sách GRN của đơn mua này</h2><p>{receipts.length} chuyến giao · thực giao {format.format(deliveredQty)} · chấp nhận {format.format(acceptedQty)}</p></div></div>{emptyReceipts.length>0&&<div className="inline-alert danger" data-vntech="po-grn-empty-warning"><b>⚠ {emptyReceipts.length}/{receipts.length} GRN RỖNG DÒNG.</b> Các chuyến giao sau không có dòng <code>goods_receipt_items</code> (khóa <code>receipt_id</code>) nên KHÔNG đối soát được số lượng theo vật tư: {emptyReceipts.map((receipt: Row) => receipt.receiptNo || receipt.id).join(" · ")}. Số liệu «đã nhận» ở trên chỉ tính theo dòng PO.</div>}<div className="table-wrap"><table className="data-table"><thead><tr><th>Mã GRN</th><th>Ngày nhận</th><th>Trạng thái giao</th><th>QC</th><th>SỐ DÒNG</th><th>Thực giao</th><th>Chấp nhận</th><th /></tr></thead><tbody>{receipts.map((receipt: Row) => <tr key={receipt.id} data-vntech="po-grn-row"><td><strong className="code">{receipt.receiptNo || receipt.id}</strong></td><td>{receipt.receivedAt ? String(receipt.receivedAt).slice(0, 10) : "—"}</td><td><StatusBadge value={receipt.bchConfirmationStatus === "confirmed" ? "BCH đã xác nhận" : receipt.postingStatus === "blocked" ? "Bị chặn ghi sổ" : "Chờ BCH xác nhận"} /></td><td><StatusBadge value={receipt.qcStatus === "accepted" ? "Đạt" : "Không đạt"} /></td><td className={isEmptyReceipt(receipt) ? "red-text" : ""}>{format.format(numeric(receiptItemCount(receipt)))}{isEmptyReceipt(receipt) && <small> ⚠ rỗng dòng</small>}</td><td>{format.format(numeric(receipt.actualDeliveredQty))}</td><td>{format.format(numeric(receipt.acceptedQty))}</td><td><button type="button" className="secondary" data-vntech="po-grn-open" onClick={() => open("receiptDetail", receipt)}>Xem chuyến giao</button></td></tr>)}{!receipts.length&&<tr><td colSpan={8}><div className="empty" data-vntech="po-grn-empty"><strong>Chưa có chuyến giao (GRN) nào cho đơn mua này.</strong><p>Nhận hàng sẽ tạo GRN đầu tiên; nếu payload không kèm GRN thì hiện trạng này KHÔNG đồng nghĩa đã nhận đủ.</p></div></td></tr>}</tbody></table></div></>; })()}</section>
    <section className="drawer-section po-timeline" data-vntech="po-timeline"><ActivityTimeline title="DÒNG THỜI GIAN ĐƠN MUA" note={`${purchaseOrderTimeline(purchaseOrder, receiptsForPurchaseOrder(data, purchaseOrder.id)).length} mốc dựng từ dữ liệu thật của PO và ${receiptsForPurchaseOrder(data, purchaseOrder.id).length} chuyến giao`} items={purchaseOrderTimeline(purchaseOrder, receiptsForPurchaseOrder(data, purchaseOrder.id))} emptyText="Chưa có mốc thời gian — payload không kèm ngày phát hành, ETA hay chuyến giao." /></section>
  </div></>}]} /></div>;
}

export { PurchaseOrderDrawer };
