// PHASE 1 (U-11) — MODULE DÙNG CHUNG TÁCH KHỎI `app/page.tsx`.
//
// Vì sao tách: `app/page.tsx` là MỘT tệp khổng lồ (hơn 4.000 dòng, hơn 250 khai báo top-level).
// Thứ tự cắt ĐÚNG (đã ghi ở `docs/agent-progress/U14-U11-KHAO-SAT.md` mục 2): tách HELPER DÙNG CHUNG trước
// (gỡ chặn IMPORT VÒNG), rồi mới tách từng màn.
//
// ⚠️ ĐIỀU KIỆN AN TOÀN (do `tools/tach-lat-cat-page.mjs` tự kiểm TRƯỚC KHI GHI): mọi tên mà các khối ở đây
// tham chiếu phải thuộc (a) khối cùng nằm trong tệp này, (b) tên có sẵn của JS, (c) tên đến từ `import` của
// `page.tsx` — công cụ SINH LẠI import đó ở đây, hoặc (d) kiểu của React ⇒ `import type … from "react"`.
// Không còn tên nào khác ⇒ KHÔNG thể tạo import vòng.

import { DataTable, StatusBadge } from "@/app/components/ui";
import { downloadBoqPriceTemplateXlsx } from "@/lib/boq-export";
import { parseSpreadsheetRows } from "@/lib/material-import";
import { BOQ_SYSTEM_CODES, CardHead, Empty, Kpi, boqControlQty, boqSystemName, downloadBlankPoPlanningTemplate, downloadPoPlanningTemplate, format, mapBoqPriceRows, moneyBillion, normalizeBoqSystemCode } from "@/lib/ui-shared";
// PHASE 2 (§21) — mở màn chi tiết PO từ màn Mua hàng; số liệu đối soát lấy từ hàm thuần dùng chung.
import { deliveryProgress, numeric } from "@/lib/p2-po-trace";
import type { AppData, Row } from "@/lib/ui-shared";
import { Fragment, useState } from "react";
function Purchasing({ data, project, open, action, canUse }: { data: AppData; project: string; open: (name: string, row?: Row) => void; action:(name:string,payload:Row)=>Promise<boolean>; canUse: boolean }) {
  const requests=data.requests.filter((row)=>(project==="ALL"||row.projectId===project)&&row.supplyStatus==="awaiting_po"); const pos=data.purchaseOrders.filter((row)=>project==="ALL"||row.projectId===project); const boqRows=data.boqItems.filter((row)=>(project==="ALL"||row.projectId===project)&&["material","component"].includes(String(row.rowRole||"material"))); const selected=project==="ALL"?null:data.projects.find((row)=>row.id===project);
  const contractRows=boqRows.filter((row)=>row.itemType!=="outside_contract"); const contract=contractRows.reduce((sum,row)=>sum+Number(row.contractQty||0)*Number(row.unitPrice||0),0); const ordered=contractRows.reduce((sum,row)=>sum+Math.min(Number(row.contractQty||0),Number(row.orderedQty||0))*Number(row.unitPrice||0),0); const received=contractRows.reduce((sum,row)=>sum+Math.min(Number(row.contractQty||0),Number(row.receivedQty||0))*Number(row.unitPrice||0),0); const paid=data.contractPayments.filter((row)=>project==="ALL"||row.projectId===project).reduce((sum,row)=>sum+Number(row.amount||0),0); const efficiency=ordered>0?Math.min(100,received/ordered*100):0;
  const [pricePreview,setPricePreview]=useState<Row[]>([]); const [priceFileName,setPriceFileName]=useState("");
  async function importPrices(file?:File){if(!file||!selected)return;try{const updates=mapBoqPriceRows(await parseSpreadsheetRows(file),boqRows);setPricePreview(updates);setPriceFileName(file.name);}catch(error){setPricePreview([]);window.alert(error instanceof Error?error.message:"Không đọc được file đơn giá hợp đồng.");}}
  async function confirmPrices(){if(!selected||!pricePreview.length)return;const ok=await action("update_boq_contract_prices",{projectId:selected.id,sourceFileName:priceFileName,updates:pricePreview.map(({boqItemId,sourceOrder,unitPrice})=>({boqItemId,sourceOrder,unitPrice}))});if(ok){setPricePreview([]);setPriceFileName("");}}
  const systemRows=BOQ_SYSTEM_CODES.map((code)=>{const rows=boqRows.filter((row)=>normalizeBoqSystemCode(row.systemCode||row.customFields?.systemCode)===code);const c=rows.filter((row)=>row.itemType!=="outside_contract");const a=c.reduce((sum,row)=>sum+Number(row.contractQty||0)*Number(row.unitPrice||0),0);const b=c.reduce((sum,row)=>sum+Math.min(Number(row.contractQty||0),Number(row.orderedQty||0))*Number(row.unitPrice||0),0);const r=c.reduce((sum,row)=>sum+Math.min(Number(row.contractQty||0),Number(row.receivedQty||0))*Number(row.unitPrice||0),0);return{code,name:boqSystemName(code),a,b,r,pct:b?Math.min(100,r/b*100):0};}).filter((row)=>row.a||row.b||row.r||project==="ALL");
  const doc={projectCode:selected?.code,projectName:selected?.name,contractNo:selected?.contractNo,rows:boqRows,fieldConfigs:data.formFieldConfigs};
  return <div className="stack module-screen purchasing-screen baseline-screen"><div className="kpi-grid"><Kpi icon="MR" label="MR chờ lập PO" value={format.format(requests.length)} note="↑ tự chuyển sau duyệt cuối"/><Kpi icon="PO" label="PO chờ giao" value={format.format(pos.filter((row)=>!["completed","completed_with_exceptions"].includes(String(row.status))).length)} note="Theo trạng thái đơn hàng" tone="violet"/><Kpi icon="DG" label="PO đang giao" value={format.format(pos.filter((row)=>String(row.status).includes("partial")||String(row.status).includes("delivery")).length)} note="Đang cập nhật giao hàng" tone="amber"/><Kpi icon="GT" label="Tổng giá trị đối chiếu" value={moneyBillion(contract)} note="Theo BOQ/Hợp đồng" tone="green"/></div>
    <section className="card purchase-cumulative-card"><div className="purchase-cumulative-head"><div><h2>LŨY KẾ MUA HÀNG ĐỐI CHIẾU BOQ/HỢP ĐỒNG</h2><p>Số liệu tính đến ngày {new Intl.DateTimeFormat("vi-VN").format(new Date())}</p></div></div><div className="purchase-summary-metrics"><article><small>TỔNG GIÁ TRỊ HỢP ĐỒNG (A)</small><strong>{moneyBillion(contract)}</strong><i><b style={{width:"100%"}}/></i><span>100% · Hợp đồng</span></article><article><small>GIÁ TRỊ ĐỐI CHIẾU (B)</small><strong>{moneyBillion(ordered)}</strong><i><b style={{width:`${contract?Math.min(100,ordered/contract*100):0}%`}}/></i><span>{contract?(ordered/contract*100).toLocaleString("vi-VN",{maximumFractionDigits:2}):"0"}% · B/A</span></article><article><small>ĐÃ NHẬN HÀNG (C)</small><strong>{moneyBillion(received)}</strong><i><b style={{width:`${contract?Math.min(100,received/contract*100):0}%`}}/></i><span>{contract?(received/contract*100).toLocaleString("vi-VN",{maximumFractionDigits:2}):"0"}% · C/A</span></article><article><small>THANH TOÁN (D)</small><strong>{moneyBillion(paid)}</strong><i><b style={{width:`${contract?Math.min(100,paid/contract*100):0}%`}}/></i><span>{contract?(paid/contract*100).toLocaleString("vi-VN",{maximumFractionDigits:2}):"0"}% · D/A</span></article><div className="purchase-efficiency-columns"><div><i className="received" style={{height:`${Math.max(6,efficiency)}%`}}/><strong>{efficiency.toLocaleString("vi-VN",{maximumFractionDigits:2})}%</strong><span>Đã nhận / Đối chiếu</span></div><div><i className="remaining" style={{height:`${Math.max(6,100-efficiency)}%`}}/><strong>{Math.max(0,100-efficiency).toLocaleString("vi-VN",{maximumFractionDigits:2})}%</strong><span>Còn lại</span></div></div></div></section>
    <div className="purchase-action-bar"><button className="secondary" onClick={()=>selected?downloadBoqPriceTemplateXlsx(doc):window.alert("Hãy chọn một dự án cụ thể.")}>⇩ TẢI MẪU ĐƠN GIÁ HĐ</button><label className={`secondary file-inline ${!selected||!canUse?"is-disabled":""}`}>⇧ NHẬP ĐƠN GIÁ HĐ<input type="file" accept=".xlsx,.csv" disabled={!selected||!canUse} onChange={(e)=>{void importPrices(e.target.files?.[0]);e.target.value="";}}/></label><button className="secondary" onClick={()=>requests[0]?downloadPoPlanningTemplate(data,requests[0]):downloadBlankPoPlanningTemplate(data)}>⇩ TẢI MẪU PO</button><button className="secondary" disabled={!requests[0]} onClick={()=>requests[0]&&open("po",requests[0])}>⇧ NHẬP PO EXCEL</button><button className="primary" disabled={!canUse||!requests[0]} onClick={()=>requests[0]&&open("po",requests[0])}>＋ PHÁT HÀNH PO</button></div>
    {/* PHASE 2 (§21) — MỞ MÀN CHI TIẾT PO: danh sách PO của phạm vi đang chọn, bấm để xem Source PR · Ordered/Received/Remaining · GRN · Timeline.
        Số liệu đi qua `deliveryProgress` (hàm thuần dùng chung) — thiếu nguồn thì hiện «chưa có nguồn», KHÔNG bịa số. */}
    <section className="card purchase-order-detail-card" data-vntech="purchasing-pos"><CardHead title="Đơn mua (PO) — mở chi tiết để truy vết" note={`${pos.length} PO trong phạm vi đang chọn · bấm «Xem chi tiết» để mở màn chi tiết PO (§21)`} />{pos.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Mã PO</th><th>Nhà cung cấp</th><th>Trạng thái</th><th>Đã đặt</th><th>Đã nhận</th><th>Còn lại</th><th /></tr></thead><tbody>{pos.map((po)=>{const progress=deliveryProgress(po);return <tr key={po.id} data-vntech="purchasing-po-row"><td><strong className="code">{po.poNo||po.id}</strong></td><td>{po.supplierName||"—"}</td><td><StatusBadge value={progress.complete?"Đã giao đủ":"Đang giao"}/></td>{progress.audit.hasData?<><td>{format.format(numeric(progress.audit.ordered))}</td><td>{format.format(numeric(progress.audit.received))}</td><td className={progress.audit.remaining>0?"red-text":"green-text"}>{format.format(numeric(progress.audit.remaining))}</td></>:<td colSpan={3}><small>chưa có nguồn — {progress.audit.reason}</small></td>}<td><button type="button" className="secondary" data-vntech="purchasing-po-open" onClick={()=>open("poDetail",po)}>Xem chi tiết PO</button></td></tr>;})}</tbody></table></div>:<Empty text="Chưa có PO nào trong phạm vi đang chọn."/>}</section>
    {pricePreview.length>0&&<section className="card price-import-preview"><header><div><strong>KIỂM TRA TRƯỚC KHI CẬP NHẬT · {priceFileName}</strong><small>{pricePreview.length} dòng hợp lệ · {pricePreview.filter((row)=>row.changed).length} dòng thay đổi</small></div><div className="row-actions"><button className="secondary" onClick={()=>setPricePreview([])}>HỦY</button><button className="primary" onClick={()=>void confirmPrices()}>XÁC NHẬN CẬP NHẬT GIÁ</button></div></header></section>}
    <section className="card purchase-system-table"><div className="table-wrap"><table className="baseline-table"><thead><tr><th>NHÓM VẬT TƯ (HỆ M&E)</th><th>HỢP ĐỒNG (A)</th><th>ĐỐI CHIẾU (B)</th><th>ĐÃ NHẬN (C)</th><th>THANH TOÁN (D)</th><th>C/E/B</th><th>TRẠNG THÁI</th></tr></thead><tbody>{systemRows.map((row)=><Fragment key={row.code}><tr className="system-total-row"><td><strong>⌄ &nbsp; HỆ {row.name.toUpperCase()}</strong></td><td><strong>{moneyBillion(row.a)}</strong></td><td><strong>{moneyBillion(row.b)}</strong></td><td><strong>{moneyBillion(row.r)}</strong></td><td><strong>{moneyBillion(row.a?paid*(row.a/Math.max(contract,1)):0)}</strong></td><td><strong>{row.pct.toLocaleString("vi-VN",{maximumFractionDigits:2})}%</strong></td><td><StatusBadge value={row.pct>=50?"Đạt kế hoạch":"Cần theo dõi"}/></td></tr></Fragment>)}{!systemRows.length&&<tr><td colSpan={7}><Empty text="Chưa có dữ liệu BOQ/Hợp đồng phát sinh trong phạm vi đang chọn."/></td></tr>}<tr className="total-row"><td><strong>TỔNG CỘNG</strong></td><td><strong>{moneyBillion(contract)}</strong></td><td><strong>{moneyBillion(ordered)}</strong></td><td><strong>{moneyBillion(received)}</strong></td><td><strong>{moneyBillion(paid)}</strong></td><td><strong>{efficiency.toLocaleString("vi-VN",{maximumFractionDigits:2})}%</strong></td><td></td></tr></tbody></table></div></section>
    <section className="card purchase-material-cumulative"><CardHead title="Chi tiết lũy kế theo vật tư" note="Chỉ hiển thị dữ liệu thực từ BOQ, đề nghị, PO và giao nhận; không nội suy dòng minh họa."/><DataTable rows={boqRows} rowKey={(row)=>String(row.id)} emptyText="Chưa có dòng vật tư BOQ/Hợp đồng cho phạm vi đang chọn." tableClassName="resizable-data-table" columns={[
  { key: "c1", header: "STT HĐ", render: (row) => <>{row.sourceOrder||"—"}</> },
  { key: "c2", header: "Mã vật tư", render: (row) => <strong>{row.materialCode||"—"}</strong> },
  { key: "c3", header: "Tên vật tư", render: (row) => <>{row.materialName||"—"}</> },
  { key: "c4", header: "ĐVT", render: (row) => <>{row.unit||"—"}</> },
  { key: "c5", header: "BOQ/HĐ", render: (row) => <>{format.format(Number(row.contractQty||0))}</> },
  { key: "c6", header: "Đã đề nghị", render: (row) => <>{format.format(Number(row.requestedQty||0))}</> },
  { key: "c7", header: "Đã duyệt mua", render: (row) => <>{format.format(Number(row.approvedQty||row.approvedPurchaseQty||0))}</> },
  { key: "c8", header: "Lũy kế PO", render: (row) => <>{format.format(Number(row.orderedQty||0))}</> },
  { key: "c9", header: "Đã nhận", render: (row) => <>{format.format(Number(row.receivedQty||0))}</> },
  { key: "c10", header: "Còn phải mua", render: (row) => <strong>{format.format(Math.max(0,boqControlQty(row)-Number(row.orderedQty||0)))}</strong> },
]}/></section>
  </div>;
}
export {
  Purchasing,
};