// PHASE 1 (U-11) — MODULE DÙNG CHUNG TÁCH KHỎI `app/page.tsx`.
//
// Vì sao tách: `app/page.tsx` là MỘT tệp khổng lồ (hơn 4.000 dòng, hơn 250 khai báo top-level).
// Thứ tự cắt ĐÚNG (đã ghi ở `docs/agent-progress/U14-U11-KHAO-SAT.md` mục 2): tách HELPER DÙNG CHUNG trước
// (gỡ chặn IMPORT VÒNG), rồi mới tách từng màn.
//
// ⚠️ ĐIỀU KIỆN AN TOÀN (do `tools/tach-lat-cat-page.mjs` tự kiểm TRƯỚC KHI GHI): mọi tên mà các khối ở đây
// tham chiếu phải thuộc (a) khối cùng nằm trong tệp này, (b) tên có sẵn của JS, (c) tên đến từ `import` của
// `page.tsx` — công cụ SINH LẠI import đó ở đây, hoặc (d) kiểu của React ⇒ `import type … from "react"`.
// Không còn tên nào khác ⇒ KHÔNG thể tạo import vòng.

import { DataTable, ListToolbar, StatusBadge } from "@/app/components/ui";
import { Kpi, UI_NOW_MS, UI_TODAY, date, format } from "@/lib/ui-shared";
import type { AppData, Row } from "@/lib/ui-shared";
import { useState } from "react";
function Receiving({ data, project, open, canUse }: { data: AppData; project: string; open: (name: string, row?: Row) => void; canUse: boolean }) {
  const [supplierFilter,setSupplierFilter]=useState("ALL"); const [statusFilter,setStatusFilter]=useState("ALL"); const [fromDate,setFromDate]=useState(""); const [toDate,setToDate]=useState("");
  const pos=data.purchaseOrders.filter((row)=>(project==="ALL"||row.projectId===project)&&!["completed","completed_with_exceptions","completed_with_shortage"].includes(String(row.status))); const filteredPos=pos.filter(r=>(supplierFilter==="ALL"||String(r.supplierId||r.supplierName)===supplierFilter)&&(statusFilter==="ALL"||String(r.status)===statusFilter)&&(!fromDate||String(r.eta||"").slice(0,10)>=fromDate)&&(!toDate||String(r.eta||"").slice(0,10)<=toDate)); const now=UI_NOW_MS; const late=pos.filter((row)=>row.eta&&new Date(row.eta).getTime()<now).length; const soon=pos.filter((row)=>{const t=new Date(row.eta||0).getTime();return t>=now&&t<=now+3*86400000;}).length; const activeSuppliers=new Set(pos.map((row)=>row.supplierId||row.supplierName).filter(Boolean)).size;
  return <div className="stack module-screen receiving-screen baseline-screen"><div className="kpi-grid"><Kpi icon="HN" label="Lịch giao hôm nay" value={format.format(pos.filter((row)=>String(row.eta||"").slice(0,10)===UI_TODAY).length)} note="↑ so với hôm qua"/><Kpi icon="TH" label="Trễ hẹn" value={format.format(late)} note="↑ cần xử lý ngay" tone="red"/><Kpi icon="SH" label="Sắp đến hạn (3 ngày)" value={format.format(soon)} note="↑ cần chủ động xác nhận" tone="amber"/><Kpi icon="NCC" label="Nhà cung cấp đang giao" value={format.format(activeSuppliers)} note="↑ PO đang thực hiện" tone="green"/></div>
    <section className="card baseline-filter-card"><div className="filter-grid receiving-filter-grid"><label><span>Nhà cung cấp</span><select value={supplierFilter} onChange={e=>setSupplierFilter(e.target.value)}><option value="ALL">Tất cả nhà cung cấp</option>{data.suppliers.map((row)=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label><span>Trạng thái</span><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="ALL">Tất cả trạng thái</option><option value="approved">Đã duyệt</option><option value="ordered">Đã đặt</option><option value="partial">Giao một phần</option></select></label><label><span>Từ ngày</span><input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)}/></label><label><span>Đến ngày</span><input type="date" value={toDate} onChange={e=>setToDate(e.target.value)}/></label><button type="button" className="secondary" onClick={()=>{setSupplierFilter("ALL");setStatusFilter("ALL");setFromDate("");setToDate("");}}>Đặt lại</button></div></section>
    <section className="card delivery-main-card"><ListToolbar title="Kế hoạch giao hàng" count={filteredPos.length} unit="bản ghi" /><DataTable rows={filteredPos} rowKey={(row) => String(row.id)} emptyText="Không còn PO phù hợp bộ lọc." columns={[{ key: "c1", header: "PO", render: (row) => <strong>{row.poNo}</strong> }, { key: "c2", header: "DỰ ÁN", render: (row) => row.projectName || row.projectCode }, { key: "c3", header: "NHÀ CUNG CẤP", render: (row) => row.supplierName }, { key: "c4", header: "HỆ M&E", render: (row) => <StatusBadge value={row.systemCode || "Điện"} /> }, { key: "c5", header: "NGÀY GIAO DỰ KIẾN", render: (row) => <><strong>{date(row.eta)}</strong><small className={row.eta && new Date(row.eta).getTime() < now ? "red-text" : "link"}>{row.eta && String(row.eta).slice(0, 10) === UI_TODAY ? "Hôm nay" : row.eta && new Date(row.eta).getTime() < now ? "Trễ hẹn" : "Sắp đến hạn"}</small></> }, { key: "c6", header: "KHỐI LƯỢNG ĐẶT", render: (row) => <>{format.format(Number(row.orderedQty || 0))}<small>PCS</small></> }, { key: "c7", header: "KHỐI LƯỢNG ĐÃ GIAO", render: (row) => { const ordered = Number(row.orderedQty || 0), actual = Number(row.actualDeliveredQty || 0), pct = ordered ? Math.min(100, actual / ordered * 100) : 0; return <>{format.format(actual)}<small>{pct.toFixed(0)}%</small></>; } }, { key: "c8", header: "CÒN THIẾU", render: (row) => { const remain = Math.max(0, Number(row.orderedQty || 0) - Number(row.actualDeliveredQty || 0)); return <><strong className={remain ? "red-text" : "green-text"}>{format.format(remain)}</strong><small>PCS</small></>; } }, { key: "c9", header: "CHỨNG CHỈ", render: (row) => <span>▧ {row.certificateCount || 0}</span> }, { key: "c10", header: "ẢNH", render: (row) => <span>▧ {row.attachmentCount || 0}</span> }, { key: "c11", header: "TRẠNG THÁI", render: (row) => { const remain = Math.max(0, Number(row.orderedQty || 0) - Number(row.actualDeliveredQty || 0)); return <StatusBadge value={remain <= 0 ? "Đã giao đủ" : row.eta && new Date(row.eta).getTime() < now ? "Trễ hẹn" : Number(row.actualDeliveredQty || 0) > 0 ? "Đang giao" : "Chưa giao"} />; } }, { key: "c12", header: "THAO TÁC", render: () => <button className="icon-mini" onClick={() => open("receipt")}>⋮</button> }]} /><div className="table-pagination functional-summary"><span>Đang hiển thị toàn bộ {filteredPos.length} bản ghi.</span></div></section>
  </div>;
}
export {
  Receiving,
};