// PHASE 1 (U-11) — MODULE DÙNG CHUNG TÁCH KHỎI `app/page.tsx`.
//
// Vì sao tách: `app/page.tsx` là MỘT tệp khổng lồ (hơn 4.000 dòng, hơn 250 khai báo top-level).
// Thứ tự cắt ĐÚNG (đã ghi ở `docs/agent-progress/U14-U11-KHAO-SAT.md` mục 2): tách HELPER DÙNG CHUNG trước
// (gỡ chặn IMPORT VÒNG), rồi mới tách từng màn.
//
// ⚠️ ĐIỀU KIỆN AN TOÀN (do `tools/tach-lat-cat-page.mjs` tự kiểm TRƯỚC KHI GHI): mọi tên mà các khối ở đây
// tham chiếu phải thuộc (a) khối cùng nằm trong tệp này, (b) tên có sẵn của JS, (c) tên đến từ `import` của
// `page.tsx` — công cụ SINH LẠI import đó ở đây, hoặc (d) kiểu của React ⇒ `import type … from "react"`.
// Không còn tên nào khác ⇒ KHÔNG thể tạo import vòng.

import { DataTable, ListToolbar, StatusBadge } from "@/app/components/ui";
import { Empty, Kpi, UI_NOW_MS, UI_TODAY, date, format } from "@/lib/ui-shared";
import type { AppData, Row } from "@/lib/ui-shared";
import { useState } from "react";
function Receiving({ data, project, open, canUse }: { data: AppData; project: string; open: (name: string, row?: Row) => void; canUse: boolean }) {
  const [supplierFilter,setSupplierFilter]=useState("ALL"); const [statusFilter,setStatusFilter]=useState("ALL"); const [fromDate,setFromDate]=useState(""); const [toDate,setToDate]=useState(""); const [card,setCard]=useState<string|null>(null);
  const pos=data.purchaseOrders.filter((row)=>(project==="ALL"||row.projectId===project)&&!["completed","completed_with_exceptions","completed_with_shortage"].includes(String(row.status))); const filteredPos=pos.filter(r=>(supplierFilter==="ALL"||String(r.supplierId||r.supplierName)===supplierFilter)&&(statusFilter==="ALL"||String(r.status)===statusFilter)&&(!fromDate||String(r.eta||"").slice(0,10)>=fromDate)&&(!toDate||String(r.eta||"").slice(0,10)<=toDate)); const now=UI_NOW_MS; const late=pos.filter((row)=>row.eta&&new Date(row.eta).getTime()<now).length; const soon=pos.filter((row)=>{const t=new Date(row.eta||0).getTime();return t>=now&&t<=now+3*86400000;}).length; const activeSuppliers=new Set(pos.map((row)=>row.supplierId||row.supplierName).filter(Boolean)).size;
  return <div className="stack module-screen receiving-screen baseline-screen"><div className="kpi-grid receiving-kpi-row"><button type="button" className="receiving-kpi-button" onClick={()=>setCard("today")} title="Xem danh sách PO giao hôm nay"><Kpi icon="HN" label="Lịch giao hôm nay" value={format.format(pos.filter((row)=>String(row.eta||"").slice(0,10)===UI_TODAY).length)} note="Bấm để xem danh sách"/></button><button type="button" className="receiving-kpi-button" onClick={()=>setCard("late")} title="Xem danh sách PO trễ hạn"><Kpi icon="TH" label="Trễ hạn" value={format.format(late)} note="Bấm để xem danh sách" tone="red"/></button><button type="button" className="receiving-kpi-button" onClick={()=>setCard("soon")} title="Xem danh sách PO sắp đến hạn"><Kpi icon="SH" label="Sắp đến hạn (3 ngày)" value={format.format(soon)} note="Bấm để xem danh sách" tone="amber"/></button><button type="button" className="receiving-kpi-button" onClick={()=>setCard("supplier")} title="Xem danh sách nhà cung cấp đang giao"><Kpi icon="NCC" label="Nhà cung cấp đang giao" value={format.format(activeSuppliers)} note="Bấm để xem danh sách" tone="green"/></button></div>
    {/* MT2-P8-11 (§6.11) — MODAL/LIST chi tiết cho TỪNG card. ⚠️ Lọc từ CHÍNH `pos` (dữ liệu thật), ⛔ KHÔNG bịa. */}
    {card&&<div className="overlay" onMouseDown={(event)=>event.target===event.currentTarget&&setCard(null)}>
      <section className="card receiving-card-detail" role="dialog" aria-modal="true" aria-label="Chi tiết card giao nhận">
        {(()=>{const titles:Record<string,string>={today:"LỊCH GIAO HÔM NAY",late:"PO TRỄ HẠN",soon:"PO SẮP ĐẾN HẠN (3 NGÀY)",supplier:"NHÀ CUNG CẤP ĐANG GIAO"};const rows = card==="today"?pos.filter((row)=>String(row.eta||"").slice(0,10)===UI_TODAY):card==="late"?pos.filter((row)=>row.eta&&new Date(row.eta).getTime()<now):card==="soon"?pos.filter((row)=>{const t=new Date(row.eta||0).getTime();return t>=now&&t<=now+3*86400000;}):pos;return <>
          <header><div><small className="document-name">{titles[card]}</small><strong>{card==="supplier"?`${activeSuppliers} nhà cung cấp · ${rows.length} PO đang giao`:`${rows.length} PO khớp tiêu chí`}</strong></div><button type="button" onClick={()=>setCard(null)} title="Đóng">×</button></header>
          {rows.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>PO</th><th>Dự án</th><th>Nhà cung cấp</th><th>Ngày giao dự kiến</th><th>Đã đặt</th><th>Đã giao</th><th>Còn thiếu</th><th>Trạng thái</th><th /></tr></thead><tbody>
            {rows.map((row)=>{const ordered=Number(row.orderedQty||0),actual=Number(row.actualDeliveredQty||0),remain=Math.max(0,ordered-actual);return <tr key={String(row.id)}>
              <td><strong className="code">{row.poNo||row.id}</strong></td><td>{row.projectName||row.projectCode||"—"}</td><td>{row.supplierName||"—"}</td>
              <td>{date(row.eta)}</td><td>{format.format(ordered)}</td><td>{format.format(actual)}</td>
              <td className={remain>0?"red-text":"green-text"}>{format.format(remain)}</td>
              <td><StatusBadge value={remain<=0?"Đã giao đủ":row.eta&&new Date(row.eta).getTime()<now?"Trễ hạn":actual>0?"Đang giao":"Chưa giao"}/></td>
              <td><button type="button" className="export-mini" onClick={()=>{setCard(null);open("receipt");}} title="Mở ghi nhận giao hàng">Ghi nhận</button></td>
            </tr>;})}
          </tbody></table></div>:<Empty text="Không có PO nào khớp tiêu chí của card này."/>}
        </>;})()}
        <div className="row-actions"><button type="button" className="secondary" onClick={()=>setCard(null)}>Đóng</button></div>
      </section>
    </div>}
    <section className="card baseline-filter-card"><div className="filter-grid receiving-filter-grid"><label><span>Nhà cung cấp</span><select value={supplierFilter} onChange={e=>setSupplierFilter(e.target.value)}><option value="ALL">Tất cả nhà cung cấp</option>{data.suppliers.map((row)=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label><span>Trạng thái</span><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="ALL">Tất cả trạng thái</option><option value="approved">Đã duyệt</option><option value="ordered">Đã đặt</option><option value="partial">Giao một phần</option></select></label><label><span>Từ ngày</span><input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)}/></label><label><span>Đến ngày</span><input type="date" value={toDate} onChange={e=>setToDate(e.target.value)}/></label><button type="button" className="secondary" onClick={()=>{setSupplierFilter("ALL");setStatusFilter("ALL");setFromDate("");setToDate("");}}>Đặt lại</button></div></section>
    <section className="card delivery-main-card"><ListToolbar title="Kế hoạch giao hàng" count={filteredPos.length} unit="bản ghi" /><DataTable rows={filteredPos} rowKey={(row) => String(row.id)} emptyText="Không còn PO phù hợp bộ lọc." columns={[{ key: "c1", header: "PO", render: (row) => <strong>{row.poNo}</strong> }, { key: "c2", header: "DỰ ÁN", render: (row) => row.projectName || row.projectCode }, { key: "c3", header: "NHÀ CUNG CẤP", render: (row) => row.supplierName }, { key: "c4", header: "HỆ M&E", render: (row) => <StatusBadge value={row.systemCode || "Điện"} /> }, { key: "c5", header: "NGÀY GIAO DỰ KIẾN", render: (row) => <><strong>{date(row.eta)}</strong><small className={row.eta && new Date(row.eta).getTime() < now ? "red-text" : "link"}>{row.eta && String(row.eta).slice(0, 10) === UI_TODAY ? "Hôm nay" : row.eta && new Date(row.eta).getTime() < now ? "Trễ hẹn" : "Sắp đến hạn"}</small></> }, { key: "c6", header: "KHỐI LƯỢNG ĐẶT", render: (row) => <>{format.format(Number(row.orderedQty || 0))}<small>PCS</small></> }, { key: "c7", header: "KHỐI LƯỢNG ĐÃ GIAO", render: (row) => { const ordered = Number(row.orderedQty || 0), actual = Number(row.actualDeliveredQty || 0), pct = ordered ? Math.min(100, actual / ordered * 100) : 0; return <>{format.format(actual)}<small>{pct.toFixed(0)}%</small></>; } }, { key: "c8", header: "CÒN THIẾU", render: (row) => { const remain = Math.max(0, Number(row.orderedQty || 0) - Number(row.actualDeliveredQty || 0)); return <><strong className={remain ? "red-text" : "green-text"}>{format.format(remain)}</strong><small>PCS</small></>; } }, { key: "c9", header: "CHỨNG CHỈ", render: (row) => <span>▧ {row.certificateCount || 0}</span> }, { key: "c10", header: "ẢNH", render: (row) => <span>▧ {row.attachmentCount || 0}</span> }, { key: "c11", header: "TRẠNG THÁI", render: (row) => { const remain = Math.max(0, Number(row.orderedQty || 0) - Number(row.actualDeliveredQty || 0)); return <StatusBadge value={remain <= 0 ? "Đã giao đủ" : row.eta && new Date(row.eta).getTime() < now ? "Trễ hẹn" : Number(row.actualDeliveredQty || 0) > 0 ? "Đang giao" : "Chưa giao"} />; } }, { key: "c12", header: "THAO TÁC", render: () => <button className="icon-mini" onClick={() => open("receipt")}>⋮</button> }]} /><div className="table-pagination functional-summary"><span>Đang hiển thị toàn bộ {filteredPos.length} bản ghi.</span></div></section>
  </div>;
}
export {
  Receiving,
};